# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-08 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trs_code', models.CharField(default='', max_length=20, verbose_name='trs_code')),
                ('trs_name', models.CharField(default='', max_length=256, verbose_name='trs_name')),
                ('fuc_desc', models.CharField(default='', max_length=1000, verbose_name='fuc_desc')),
                ('eng_name', models.CharField(default='', max_length=20, verbose_name='eng_name')),
                ('chinese_name', models.CharField(default='', max_length=20, verbose_name='chinese_name')),
                ('data_type', models.CharField(default='', max_length=20, verbose_name='data_type')),
                ('data_len', models.CharField(default='', max_length=20, verbose_name='data_len')),
                ('input_flag', models.CharField(default='', max_length=1, verbose_name='input_flag')),
                ('remark', models.CharField(default='', max_length=20, verbose_name='remark')),
            ],
        ),
    ]
