# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-08 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='input',
            field=models.CharField(default='', max_length=30, verbose_name='input'),
        ),
        migrations.AddField(
            model_name='api',
            name='output',
            field=models.CharField(default='', max_length=30, verbose_name='output'),
        ),
        migrations.AlterField(
            model_name='api',
            name='trs_name',
            field=models.CharField(default='', max_length=200, verbose_name='trs_name'),
        ),
    ]
