# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-08 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_api_list_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='input',
            new_name='in_output',
        ),
        migrations.RenameField(
            model_name='api',
            old_name='list_flag',
            new_name='list',
        ),
        migrations.RemoveField(
            model_name='api',
            name='output',
        ),
    ]
