# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-08 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190508_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='in_output',
            new_name='i_output',
        ),
    ]
