# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-09 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190508_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='data_len',
        ),
        migrations.RemoveField(
            model_name='api',
            name='list',
        ),
    ]
