# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-09 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190509_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='in_output',
        ),
        migrations.RemoveField(
            model_name='api',
            name='input_flag',
        ),
        migrations.AddField(
            model_name='api',
            name='flag',
            field=models.CharField(default='', max_length=30, verbose_name='输入输出标识'),
        ),
        migrations.AddField(
            model_name='api',
            name='required',
            field=models.CharField(default='', max_length=1, verbose_name='是否必输'),
        ),
        migrations.AlterField(
            model_name='api',
            name='chinese_name',
            field=models.CharField(default='', max_length=20, verbose_name='中文名'),
        ),
        migrations.AlterField(
            model_name='api',
            name='data_type',
            field=models.CharField(default='', max_length=20, verbose_name='数据类型'),
        ),
        migrations.AlterField(
            model_name='api',
            name='eng_name',
            field=models.CharField(default='', max_length=20, verbose_name='英文名'),
        ),
        migrations.AlterField(
            model_name='api',
            name='fuc_desc',
            field=models.CharField(default='', max_length=1000, verbose_name='交易描述'),
        ),
        migrations.AlterField(
            model_name='api',
            name='remark',
            field=models.CharField(default='', max_length=20, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='api',
            name='trs_code',
            field=models.CharField(default='', max_length=20, verbose_name='交易码'),
        ),
        migrations.AlterField(
            model_name='api',
            name='trs_name',
            field=models.CharField(default='', max_length=200, verbose_name='交易名称'),
        ),
    ]
