# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-09 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190509_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='chinese_name',
            field=models.CharField(default='', max_length=200, verbose_name='中文名'),
        ),
        migrations.AlterField(
            model_name='api',
            name='eng_name',
            field=models.CharField(default='', max_length=200, verbose_name='英文名'),
        ),
    ]
