# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-09 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190509_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='remark',
            field=models.CharField(default='', max_length=2000, verbose_name='备注'),
        ),
    ]
