# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-01 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custinfo',
            options={'verbose_name': '客户信息列表', 'verbose_name_plural': '客户信息列表'},
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='querymonth',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='账单月份'),
        ),
    ]
