# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-27 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='custInfo',
            fields=[
                ('object_id', models.CharField(blank=True, default='', max_length=64, verbose_name='uuid')),
                ('crawldate', models.CharField(blank=True, default='', max_length=255, primary_key=True, serialize=False, verbose_name='信息获取日期')),
                ('rangeno', models.CharField(blank=True, db_index=True, default='', max_length=10, verbose_name='号段')),
                ('phoneno', models.CharField(blank=True, max_length=11, verbose_name='手机号码')),
                ('paytype', models.CharField(blank=True, max_length=255, null=True, verbose_name='付费类型')),
                ('querymonth', models.CharField(blank=True, max_length=10, null=True, verbose_name='查询月份')),
                ('acctflag', models.CharField(blank=True, max_length=255, null=True, verbose_name='账户标识')),
                ('debtfee', models.CharField(blank=True, max_length=255, null=True, verbose_name='欠费金额')),
                ('fixtype', models.CharField(blank=True, max_length=255, null=True, verbose_name='融合类型')),
                ('payname', models.CharField(blank=True, max_length=255, null=True, verbose_name='付费名称')),
                ('prodname', models.CharField(blank=True, max_length=255, null=True, verbose_name='产品名称')),
                ('fee', models.CharField(blank=True, max_length=255, null=True, verbose_name='实时话费')),
                ('openflag', models.CharField(blank=True, max_length=255, null=True, verbose_name='开通状态')),
                ('custbrand', models.CharField(blank=True, max_length=255, null=True, verbose_name='客户品牌')),
                ('actualbal', models.CharField(blank=True, max_length=255, null=True, verbose_name='实时结余')),
                ('custlocation', models.CharField(blank=True, max_length=255, null=True, verbose_name='客户市县')),
                ('creditbal', models.CharField(blank=True, max_length=255, null=True, verbose_name='信用额度')),
                ('totalfee', models.CharField(blank=True, max_length=255, null=True, verbose_name='总计计费应收')),
                ('actualfee', models.CharField(blank=True, max_length=255, null=True, verbose_name='总计实际应收')),
            ],
            options={
                'verbose_name': '客户信息',
                'verbose_name_plural': '客户信息',
            },
        ),
    ]
