# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-13 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trs_name', models.CharField(default='', max_length=200, verbose_name='交易名称')),
                ('fuc_desc', models.CharField(default='', max_length=1000, verbose_name='交易描述')),
                ('flag', models.CharField(default='', max_length=30, verbose_name='输入输出标识')),
                ('eng_name', models.CharField(default='', max_length=200, verbose_name='英文名')),
                ('chinese_name', models.CharField(default='', max_length=200, verbose_name='中文名')),
                ('data_type', models.CharField(default='', max_length=20, verbose_name='数据类型')),
                ('required', models.CharField(default='', max_length=10, verbose_name='是否必输')),
                ('remark', models.CharField(default='', max_length=2000, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('trs_code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='交易码')),
                ('trs_name', models.CharField(default='', max_length=200, verbose_name='交易名称')),
                ('fuc_desc', models.CharField(default='', max_length=1000, verbose_name='交易描述')),
            ],
        ),
        migrations.AddField(
            model_name='details',
            name='trs_code',
            field=models.ForeignKey(default='', max_length=20, on_delete=django.db.models.deletion.CASCADE, to='interface.Header', verbose_name='交易码'),
        ),
    ]
